import 'bootstrap/dist/css/bootstrap.css'
import './globals.css'
import { robotoFlex, robotoSlab } from './utils/fonts';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoSlab.variable} ${robotoFlex.className}`}>{children}</body>
    </html>
  )
}
